apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
      buildkite.com/project-slug: nutrien/digital-k8s
      backstage.io/techdocs-ref: url:https://github.com/jsqcloud/backstage/tree/master
      github.com/project-slug: jsqcloud/backstage
      backstage.io/code-coverage: enabled
      sentry.io/project-slug: au-digital-hub
      backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=au-customer-domain'
      backstage.io/kubernetes-id: au-customer-domain
  name: artist-lookup
  description: Artist Lookup
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
